from typing import TypedDict

class AgentState(TypedDict):
    """
    Represents the state of an agent as a typed dictionary.

    Keys:
        input (str): The input provided to the agent (e.g., user prompt).
        output (str): The output or response generated by the agent.
        username (str): The identifier of the user associated with this state.
        reminder (str): A reminder or additional context the agent needs to keep.
    """
    input: str
    output: str
    username: str
    reminder: str